django_news/comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'

urlpatterns = [
    path('<int:pk>/create/', views.create_comment_view, name='create'),
    path('<int:pk>/delete/', views.delete_comment_view, name='delete'),
]

django_news/django_news/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from posts.views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index'),
    path('users/', include('users.urls', namespace='users')),
    path('news/', include('posts.urls', namespace='posts')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_news/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.post_create_view, name='create'),
    path('<int:pk>/', views.post_detail_view, name='detail'),
    path('<int:pk>/update/', views.post_update_view, name='update'),
    path('<int:pk>/delete/', views.post_delete_view, name='delete'),
    path('generate-pdf/', views.generate_pdf, name='generate_pdf'),
]

django_news/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.user_login_view, name='login'),
    path('register/', views.user_registration_view, name='register'),
    path('logout/', views.user_logout_view, name='logout'),
]

django_news/comments/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Comment(models.Model):
    post = models.ForeignKey('posts.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

django_news/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

django_news/users/models.py
from django.db import models

# Create your models here.

django_news/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

django_news/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

django_news/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2')
        labels = {
            'username': 'Username:',
            'first_name': 'First name:',
            'last_name': 'Last name:',
            'password1': 'Password:',
        }
        widgets = {
            'username': forms.TextInput(),
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
            'password1': forms.PasswordInput(),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_customer = True
        if commit:
            user.save()
        return user

django_news/comments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CommentForm
from .models import Comment



def create_comment_view(request, pk):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        form.save(commit=False)
        form.instance.post_id = pk
        form.instance.author = request.user
        form.save()
        return redirect('index')
    return render(request, 'comments/create_comment.html', {'form': form})


def delete_comment_view(request, pk):
    comment = get_object_or_404(Comment, pk=pk, author=request.user)
    if request.method == 'POST':
        comment.delete()
        return redirect('index')
    return render(request, 'comments/delete_comment.html', {'comment': comment})

django_news/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from posts.models import Post
from .forms import PostForm
from django.http import FileResponse
from reportlab.pdfgen import canvas

def generate_pdf(request):
    response = FileResponse(generate_pdf_file(), 
                            as_attachment=True, 
                            filename='book_catalog.pdf')
    return response
 
 
def generate_pdf_file():
    from io import BytesIO
 
    buffer = BytesIO()
    p = canvas.Canvas(buffer)
 
    # Create a PDF document
    books = Post.objects.all()
    p.drawString(100, 750, "News Catalog")
 
    y = 700
    for book in books:
        p.drawString(100, y, f"Title: {book.title}")
        p.drawString(100, y - 20, f"Content: {book.content}")
        p.drawString(100, y - 40, f"Author: {book.created_by}")
        y -= 60
 
    p.showPage()
    p.save()
 
    buffer.seek(0)
    return buffer


def index_view(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def post_detail_view(request, pk):
    post = Post.objects.get(pk=pk)
    context = {
        'post': post,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def post_create_view(request):
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        form.save(commit=False)
        form.instance.created_by = request.user
        form.save()
        return redirect('index')
    return render(request, 'posts/create_form.html', {'form': form})


@login_required
def post_update_view(request, pk):
    post = get_object_or_404(Post, pk=pk, created_by=request.user)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('index')
    return render(request, 'posts/update_form.html', {'form': form})


def post_delete_view(request, pk):
    post = get_object_or_404(Post, pk=pk, created_by=request.user)
    if request.method == 'POST':
        post.delete()
        return redirect('index')
    return render(request, 'posts/delete_form.html', {'post': post})

django_news/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .forms import UserRegistrationForm, UserLoginForm


def user_login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('index'))
    else:
        form = UserLoginForm(request)
    return render(request, 'users/login.html', {'form': form})


def user_registration_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def user_logout_view(request):
    if request.method == 'POST':
        logout(request)
    return redirect(reverse('index'))

django_news/comments/templates/comments/create_comment.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create Comment</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

django_news/comments/templates/comments/delete_comment.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <h1>Delete Comment</h1>
    <p>Are you sure you want to delete this comment?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
{% else %}
    <h1>Please register</h1>
{% endif %}
{% endblock %}

django_news/posts/templates/posts/create_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create a new news</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

django_news/posts/templates/posts/delete_form.html
{% extends 'base.html' %}

{% block content %}
    
    <h1>Delete news</h1>
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
    <a href="{% url 'posts:detail' post.id %}">Cancel</a>
    
{% endblock %}

django_news/posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>Text: {{ post.content }}</p>
    <p>Created by: {{ post.created_by.username }}</p>
    <p><a href="{% url 'posts:generate_pdf' %}" download>Download Book Catalog (PDF)</a></p>
    {% if user.is_authenticated %}
        <a href="{% url 'posts:update' post.id %}">Edit</a>
        <a href="{% url 'posts:delete' post.id %}">Delete</a>
        <hr>
        <a href="{% url 'comments:create' post.id %}">Add Comment</a>
        <hr>
    {% endif %}
        <h2>Comments</h2>
        {% for comment in post.comments.all %}
            <p>Created by: {{ comment.author.username }}</p>
            <p>Text: {{ comment.content }}</p>
            {% if user.is_authenticated %}
                <a href="{% url 'comments:delete' comment.id %}">Delete</a>
            {% endif %}
            <hr>
        {% endfor %}
    

{% endblock %}

django_news/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
    <h2>News: </h2>
    {% for post in posts %}
        <h3>Title: {{ post.title }}</h3>
        <p>Text:{{ post.content }}</p>
        <p>Author : {{ post.created_by }}</p>
        <a href="{{ post.get_absolute_url }}">Detail</a>
        <hr>
    {% endfor %}
{% endblock %}

django_news/posts/templates/posts/update_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update news</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

django_news/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
{% if user.is_authenticated %}
    <form method="POST" action="{% url 'users:logout' %}">
        {% csrf_token %}
    <p>Hello, {{ user.username }}</p><button type="submit">Logout</button>
    </form>
    <br>
    <a href="{% url 'posts:create' %}">Create News</a>
{% else %}
    <a href="{% url 'users:login' %}">Login</a>
    <a href="{% url 'users:register' %}">Register</a>
{% endif %}
{% block content %} {% endblock %}
</body>
</html>

django_news/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <h2>Login</h2>
    <form method="POST" action="">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">Login</button>
    </form>
{% endblock %}

django_news/users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
    <h2>Register</h2>
    <form method="POST" action="">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">Register</button>
    </form>
{% endblock %}